// src/store/useOrderStore.js
//
// Order store backed by Supabase. Same public interface as the previous
// localStorage version, so components don't need to change much.

import { create } from 'zustand';
import { supabase } from '../api/supabase';

// Convert a Supabase row (snake_case, flat receipt columns) to the
// frontend shape (camelCase, nested receipt object).
function fromRow(row) {
  return {
    id: row.id,
    userId: row.user_id,
    status: row.status,
    customer: row.customer,
    address: row.address,
    delivery: row.delivery,
    items: row.items,
    subtotal: Number(row.subtotal),
    discount: Number(row.discount),
    coupon: row.coupon,
    shipping: Number(row.shipping),
    total: Number(row.total),
    paymentMethod: row.payment_method,
    receipt: row.receipt_path
      ? {
          fileName: row.receipt_file_name,
          uploadedAt: row.receipt_uploaded_at,
          path: row.receipt_path,
        }
      : null,
    createdAt: row.created_at,
  };
}

// Convert frontend order data to Supabase insert columns.
function toInsertRow(orderData) {
  return {
    user_id: orderData.userId,
    status: orderData.status,
    customer: orderData.customer,
    address: orderData.address,
    delivery: orderData.delivery,
    items: orderData.items,
    subtotal: orderData.subtotal,
    discount: orderData.discount,
    coupon: orderData.coupon,
    shipping: orderData.shipping,
    total: orderData.total,
    payment_method: orderData.paymentMethod,
    // id is generated by a trigger; receipt columns stay null.
  };
}

export const useOrderStore = create((set, get) => ({
  orders: [],
  loading: false,
  error: null,

  fetchOrders: async () => {
    set({ loading: true, error: null });
    const { data, error } = await supabase
      .from('orders')
      .select('*')
      .order('created_at', { ascending: false });
    if (error) {
      set({ loading: false, error: error.message });
      return;
    }
    set({ orders: (data ?? []).map(fromRow), loading: false });
  },

  // Used by pages that need a single order by ID (PaymentPage, OrderDetailsPage).
  // Checks the cache first; falls back to a Supabase query.
  fetchOrderById: async (id) => {
    const cached = get().orders.find((o) => o.id === id);
    if (cached) return cached;

    const { data, error } = await supabase
      .from('orders')
      .select('*')
      .eq('id', id)
      .maybeSingle();
    if (error || !data) return null;

    const order = fromRow(data);
    set((state) => ({
      orders: [order, ...state.orders.filter((o) => o.id !== order.id)],
    }));
    return order;
  },

  addOrder: async (orderData) => {
    const { data, error } = await supabase
      .from('orders')
      .insert(toInsertRow(orderData))
      .select()
      .single();
    if (error) throw new Error(error.message);

    const created = fromRow(data);
    set((state) => ({ orders: [created, ...state.orders] }));
    return created.id;
  },

  uploadReceipt: async (order, file) => {
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) throw new Error('Not authenticated');

    const ext = file.name.split('.').pop() || 'bin';
    const path = `${user.id}/${order.id}/receipt.${ext}`;

    const { error: uploadError } = await supabase.storage
      .from('receipts')
      .upload(path, file, { upsert: true, contentType: file.type });
    if (uploadError) throw new Error(uploadError.message);

    const { data, error } = await supabase
      .from('orders')
      .update({
        receipt_path: path,
        receipt_file_name: file.name,
        receipt_uploaded_at: new Date().toISOString(),
        status: 'verifying',
      })
      .eq('id', order.id)
      .select()
      .single();
    if (error) throw new Error(error.message);

    const updated = fromRow(data);
    set((state) => ({
      orders: state.orders.map((o) => (o.id === order.id ? updated : o)),
    }));
    return updated;
  },

  // Admin-only. RLS enforces that.
  updateOrderStatus: async (id, status) => {
    const { data, error } = await supabase
      .from('orders')
      .update({ status })
      .eq('id', id)
      .select()
      .single();
    if (error) throw new Error(error.message);

    const updated = fromRow(data);
    set((state) => ({
      orders: state.orders.map((o) => (o.id === id ? updated : o)),
    }));
    return updated;
  },

  // Synchronous cache lookup. Returns null if not cached.
  getOrderById: (id) => get().orders.find((o) => o.id === id) ?? null,

  clear: () => set({ orders: [], error: null }),
}));